name: go-example
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * 2-6' #trigado a cada 15 min, de segunda à sábado.

env:
  FILE_NAME: hello-server
  
jobs:
  build-go:
    name: Build GO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go
      
    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
    
  download-and-run-linux:
      runs-on: ubuntu-latest
      needs: build-go
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Download Linux Artifact
          uses: actions/download-artifact@v4
          with:
            name: linux

        - name: List files in current directory
          run: ls -la

        - name: Make run.sh executable
          run: chmod +x ./run.sh

        - name: Run Script
          run: ./run.sh
  
  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows

      - name: List files in current directory
        run: dir
